# command to run tests
language: python
python:
  - "3.7-dev"  # 3.7 development branch
virtualenv:
  system_site_packages: true
install: "pip install requests"

script: python Localization.py  # or py.test for Python versions 3.5 and below
